set wrap
set undofile
set clipboard=unnamedplus

set expandtab
set shiftwidth=4
set tabstop=4
"set smartindent

set termguicolors
colorscheme sunbather 
set background=dark
syntax on
hi Normal guibg=#161616


set number 
set relativenumber 

" Abbreviations
cabbrev W w
cabbrev Q q
cabbrev Q! q!
cabbrev Wq wq

nnoremap Q <Nop>

nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

"tabs for makefile ;;
autocmd FileType make setlocal noexpandtab tabstop=4 shiftwidth=4
:nnoremap <F5> :make -B<CR>
