#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 0
bspc config window_gap 0

bspc config pointer_motion_interval 1
bspc config focus_follows_pointer true

bspc wm -a
